name: gitartwork from a contribution graph
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    name: Make gitartwork SVG
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jasineri/gitartwork@v1
        with:
          # Use this username's contribution graph
          user_name: rakibulislam8226
          # Text on contribution graph
          text: RAKIB
      - uses: jasineri/simple-push-action@v1
